/**
 * Single source of truth for session type styling.
 * Used by SessionCard, SessionDetail (and sub-components).
 */
export const SESSION_TYPE_CONFIG = {
  running: {
    label: 'Course',
    badgeClass:    'bg-emerald-100 text-emerald-700',
    intensityColor:'text-emerald-600',
    completedBtn:  'bg-emerald-100 text-emerald-700 border border-emerald-300',
    pendingBtn:    'bg-emerald-500 text-white',
    cardBg:        'bg-emerald-50',
    borderColor:   'border-emerald-400',
    labelColor:    'text-emerald-600',
    badgeBg:       'bg-emerald-100 text-emerald-700',
    checkActive:   'border-emerald-500 bg-emerald-500 text-white',
    checkInactive: 'border-emerald-300 text-transparent',
  },
  strength: {
    label: 'Renforcement',
    badgeClass:    'bg-blue-100 text-blue-700',
    intensityColor:'text-blue-600',
    completedBtn:  'bg-blue-100 text-blue-700 border border-blue-300',
    pendingBtn:    'bg-blue-500 text-white',
    cardBg:        'bg-blue-50',
    borderColor:   'border-blue-400',
    labelColor:    'text-blue-600',
    badgeBg:       'bg-blue-100 text-blue-700',
    checkActive:   'border-blue-500 bg-blue-500 text-white',
    checkInactive: 'border-blue-300 text-transparent',
  },
  hyrox: {
    label: 'Hyrox',
    badgeClass:    'bg-amber-100 text-amber-700',
    intensityColor:'text-amber-600',
    completedBtn:  'bg-amber-100 text-amber-700 border border-amber-300',
    pendingBtn:    'bg-amber-500 text-white',
    cardBg:        'bg-amber-50',
    borderColor:   'border-amber-500',
    labelColor:    'text-amber-600',
    badgeBg:       'bg-amber-100 text-amber-700',
    checkActive:   'border-amber-500 bg-amber-500 text-white',
    checkInactive: 'border-amber-300 text-transparent',
  },
  brick: {
    label: 'Brick',
    badgeClass:    'bg-cyan-100 text-cyan-700',
    intensityColor:'text-cyan-600',
    completedBtn:  'bg-cyan-100 text-cyan-700 border border-cyan-300',
    pendingBtn:    'bg-cyan-500 text-white',
    cardBg:        'bg-cyan-50',
    borderColor:   'border-cyan-500',
    labelColor:    'text-cyan-700',
    badgeBg:       'bg-cyan-100 text-cyan-700',
    checkActive:   'border-cyan-500 bg-cyan-500 text-white',
    checkInactive: 'border-cyan-300 text-transparent',
  },
  mobility: {
    label: 'Mobilité',
    badgeClass:    'bg-violet-100 text-violet-700',
    intensityColor:'text-violet-600',
    completedBtn:  'bg-violet-100 text-violet-700 border border-violet-300',
    pendingBtn:    'bg-violet-500 text-white',
    cardBg:        'bg-violet-50',
    borderColor:   'border-violet-300',
    labelColor:    'text-violet-500',
    badgeBg:       'bg-violet-100 text-violet-600',
    checkActive:   'border-violet-400 bg-violet-400 text-white',
    checkInactive: 'border-violet-200 text-transparent',
  },
  recovery: {
    label: 'Récupération',
    badgeClass:    'bg-gray-100 text-gray-600',
    intensityColor:'text-gray-500',
    completedBtn:  'bg-gray-100 text-gray-600 border border-gray-300',
    pendingBtn:    'bg-gray-400 text-white',
    cardBg:        'bg-gray-50',
    borderColor:   'border-gray-300',
    labelColor:    'text-gray-500',
    badgeBg:       'bg-gray-100 text-gray-500',
    checkActive:   'border-gray-400 bg-gray-400 text-white',
    checkInactive: 'border-gray-300 text-transparent',
  },
  race: {
    label: '🏁 Race Day',
    badgeClass:    'bg-red-100 text-red-700',
    intensityColor:'text-red-600',
    completedBtn:  'bg-red-100 text-red-700 border border-red-300',
    pendingBtn:    'bg-red-500 text-white',
    cardBg:        'bg-red-50',
    borderColor:   'border-red-500',
    labelColor:    'text-red-600',
    badgeBg:       'bg-red-100 text-red-700',
    checkActive:   'border-red-500 bg-red-500 text-white',
    checkInactive: 'border-red-300 text-transparent',
  },
}

export function getSessionTypeConfig(type) {
  return SESSION_TYPE_CONFIG[type] ?? SESSION_TYPE_CONFIG.running
}
