/**
 * Single source of truth for session type styling.
 * Used by SessionCard, SessionDetail (and sub-components).
 */
export const SESSION_TYPE_CONFIG = {
  running: {
    label: 'Course',
    icon:  '🏃',
    iconBg:        'bg-emerald-100',
    badgeClass:    'bg-emerald-100 text-emerald-700',
    intensityColor:'text-emerald-600',
    dotBg:         'bg-emerald-500',
    completedBtn:  'bg-emerald-100 text-emerald-700 border border-emerald-200',
    pendingBtn:    'bg-emerald-500 text-white',
    cardBg:        'bg-emerald-50',
    borderColor:   'border-emerald-400',
    labelColor:    'text-emerald-600',
    badgeBg:       'bg-emerald-100 text-emerald-700',
    checkActive:   'border-emerald-500 bg-emerald-500',
    checkInactive: 'border-stone-200',
    heroBg:        'bg-emerald-600',
    heroText:      'text-emerald-100',
  },
  strength: {
    label: 'Renforcement',
    icon:  '💪',
    iconBg:        'bg-blue-100',
    badgeClass:    'bg-blue-100 text-blue-700',
    intensityColor:'text-blue-600',
    dotBg:         'bg-blue-500',
    completedBtn:  'bg-blue-100 text-blue-700 border border-blue-200',
    pendingBtn:    'bg-blue-500 text-white',
    cardBg:        'bg-blue-50',
    borderColor:   'border-blue-400',
    labelColor:    'text-blue-600',
    badgeBg:       'bg-blue-100 text-blue-700',
    checkActive:   'border-blue-500 bg-blue-500',
    checkInactive: 'border-stone-200',
    heroBg:        'bg-blue-600',
    heroText:      'text-blue-100',
  },
  hyrox: {
    label: 'Hyrox',
    icon:  '⚡',
    iconBg:        'bg-amber-100',
    badgeClass:    'bg-amber-100 text-amber-700',
    intensityColor:'text-amber-600',
    dotBg:         'bg-amber-500',
    completedBtn:  'bg-amber-100 text-amber-700 border border-amber-200',
    pendingBtn:    'bg-amber-500 text-white',
    cardBg:        'bg-amber-50',
    borderColor:   'border-amber-500',
    labelColor:    'text-amber-600',
    badgeBg:       'bg-amber-100 text-amber-700',
    checkActive:   'border-amber-500 bg-amber-500',
    checkInactive: 'border-stone-200',
    heroBg:        'bg-amber-500',
    heroText:      'text-amber-100',
  },
  brick: {
    label: 'Brick',
    icon:  '🔗',
    iconBg:        'bg-cyan-100',
    badgeClass:    'bg-cyan-100 text-cyan-700',
    intensityColor:'text-cyan-600',
    dotBg:         'bg-cyan-500',
    completedBtn:  'bg-cyan-100 text-cyan-700 border border-cyan-200',
    pendingBtn:    'bg-cyan-500 text-white',
    cardBg:        'bg-cyan-50',
    borderColor:   'border-cyan-500',
    labelColor:    'text-cyan-700',
    badgeBg:       'bg-cyan-100 text-cyan-700',
    checkActive:   'border-cyan-500 bg-cyan-500',
    checkInactive: 'border-stone-200',
    heroBg:        'bg-cyan-600',
    heroText:      'text-cyan-100',
  },
  mobility: {
    label: 'Mobilité',
    icon:  '🧘',
    iconBg:        'bg-violet-100',
    badgeClass:    'bg-violet-100 text-violet-700',
    intensityColor:'text-violet-600',
    dotBg:         'bg-violet-500',
    completedBtn:  'bg-violet-100 text-violet-700 border border-violet-200',
    pendingBtn:    'bg-violet-500 text-white',
    cardBg:        'bg-violet-50',
    borderColor:   'border-violet-300',
    labelColor:    'text-violet-500',
    badgeBg:       'bg-violet-100 text-violet-600',
    checkActive:   'border-violet-400 bg-violet-400',
    checkInactive: 'border-stone-200',
    heroBg:        'bg-violet-600',
    heroText:      'text-violet-100',
  },
  recovery: {
    label: 'Récupération',
    icon:  '😴',
    iconBg:        'bg-stone-100',
    badgeClass:    'bg-stone-100 text-stone-600',
    intensityColor:'text-stone-500',
    dotBg:         'bg-stone-400',
    completedBtn:  'bg-stone-100 text-stone-600 border border-stone-200',
    pendingBtn:    'bg-stone-400 text-white',
    cardBg:        'bg-stone-50',
    borderColor:   'border-stone-300',
    labelColor:    'text-stone-500',
    badgeBg:       'bg-stone-100 text-stone-500',
    checkActive:   'border-stone-400 bg-stone-400',
    checkInactive: 'border-stone-200',
    heroBg:        'bg-slate-600',
    heroText:      'text-slate-200',
  },
  race: {
    label: '🏁 Race Day',
    icon:  '🏁',
    iconBg:        'bg-red-100',
    badgeClass:    'bg-red-100 text-red-700',
    intensityColor:'text-red-600',
    dotBg:         'bg-red-500',
    completedBtn:  'bg-red-100 text-red-700 border border-red-200',
    pendingBtn:    'bg-red-500 text-white',
    cardBg:        'bg-red-50',
    borderColor:   'border-red-500',
    labelColor:    'text-red-600',
    badgeBg:       'bg-red-100 text-red-700',
    checkActive:   'border-red-500 bg-red-500',
    checkInactive: 'border-stone-200',
    heroBg:        'bg-red-600',
    heroText:      'text-red-100',
  },
}

export function getSessionTypeConfig(type) {
  return SESSION_TYPE_CONFIG[type] ?? SESSION_TYPE_CONFIG.running
}
